# Generated by Django 4.0.6 on 2022-12-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0025_alter_meal_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roomNumber',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
